apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: projektcms-v01-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: CLIENT_ID
              value: "d579615447442-5fitnfqgobfsnqsh7h1tfvjj0ncelfqb.apps.googleusercontent.com"
            - name: CLIENT_SECRET
              value: "dGOCSPX-kP8VMWRyI2uhKC2YqRpn5iEMj9Hk"
            - name: DB_USER
              value: "meta"
            - name: DB_PASSWORD
              value: "meta2024!"
            - name: DB_HOST
              value: "database"
            - name: DB_NAME
              value: "meta_db"
            - name: ENABLE_DEBUG
              value: "TRUE"
            - name: JWT_SECRET
              value: "meta11"
            - name: DB_PORT
              value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: projektcms-v01-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://backend:3001"

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: projektcms-v01-database:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
      # healthCheck:
      #   exec:
      #     command:
      #       - "mysqladmin"
      #       - "ping"
      #       - "-h"
      #       - "localhost"
      #   initialDelaySeconds: 15
      #   periodSeconds: 10
      #   timeoutSeconds: 5
      #   failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: nginx:alpine
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
            - name: nginx-certs
              mountPath: /etc/nginx/certs
      volumes:
        - name: nginx-conf
          hostPath:
            path: /etc/nginx
        - name: nginx-certs
          hostPath:
            path: /etc/nginx
