version: "3.8"
services:
  backend:
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile.backend
    # container_name: backend
    image:  jyldyz0610/cmsbackend:latest
    
    
    ports:
      - "3001:3001"
    environment:
      - CLIENT_ID=deine_client_id
      - CLIENT_SECRET=dein_client_geheimnis
      - DB_USER=meta
      - DB_PASSWORD=meta2024!
      - DB_HOST=database
      - DB_NAME=meta_db
      - ENABLE_DEBUG=TRUE
      - JWT_SECRET=meta11
      - DB_PORT=3306
    depends_on:
      database:
        condition: service_healthy

  frontend:
    # build: 
    #   context: ./frontend
    #   dockerfile: Dockerfile.frontend
    image:  jyldyz0610/cmsfrontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
  database:
    image: jyldyz0610/cmsdatabase:latest
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile.db
    container_name: database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  proxy:
    image: nginx:alpine
    ports:
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend