-- CREATE DATABASE IF NOT EXISTS meta_db;
DROP DATABASE IF EXISTS meta_db;
CREATE DATABASE IF NOT EXISTS `meta_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'meta'@'%' IDENTIFIED BY 'meta2024!';

GRANT SELECT, CREATE, UPDATE, INSERT, DELETE ON meta_db.* TO 'meta'@'%';

FLUSH PRIVILEGES;
