version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" # Port Mapping für das Backend
    restart: always # Container bei Bedarf automatisch neu starten

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Port Mapping für das Frontend
    restart: always # Container bei Bedarf automatisch neu starten
    depends_on:
      - backend # Das Frontend hängt vom Backend ab

  mysql:
    build: ./mysql
    ports:
      - "3306:3306" # Port Mapping für das mysql
    restart: always # Container bei Bedarf automatisch neu starten
    depends_on:
      - backend # mysql hängt vom Backend ab
