apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectcms
  labels:
    app: projectcms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectcms
  template:
    metadata:
      labels:
        app: projectcms
    spec:
      containers:
      - name: projectcms
        image: jyldyz0610/cmsfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "https://backend.devops-knowledge.de"
        - name: TEST 
          value: "test"
      restartPolicy: Always


