apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jyldyz0610/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          env:
            - name: FRONTEND_URL
              value: "https://frontend.devops-knowledge.de"
            - name: BACKEND_URL
              value: "https://backend.devops-knowledge.de"
            - name: CLIENT_ID
              value: "853117883137-rnjs8as6ad32jcv61phal2pgd4tve2a1.apps.googleusercontent.com"  
            - name: CLIENT_SECRET
              value: "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"
            - name: DB_USER
              value: "meta"
            - name: DB_PASSWORD
              value: "meta2024!"
            - name: DB_HOST
              value: "database"
            - name: DB_NAME
              value: "meta_db"
            - name: ENABLE_DEBUG
              value: "TRUE"
            - name: JWT_SECRET
              value: "meta11"
            - name: DB_PORT
              value: "3306"